### ISSUE TITLE
Add oAuth1 support

### ISSUE THREAD

**Issue by patricks** [OAuthSwift/OAuthSwiftAlamofire#3]
Please add oAuth 1.0 support

**Comment by phimage** [comment]
oauth2 have static header after authentification, that's why there is an helper to create an alamofire Manager with this preconfigured header

oauth1 need to sign each request according to the url and query parameters, so there is no helper to create a Manager

So you can only use the two other methods in readme

Then maybe there is in Alamofire a way to inject signature for each request with a callback/handler/delegate
But until know I have not found where to do it

**Comment by phimage** [comment]
I will add a RequestAdapter, see alamofire Doc, inpired from AccessTokenAdapter
